# Generated by Django 5.0.6 on 2024-06-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectedobject',
            options={'verbose_name': 'Обнаруженный объект', 'verbose_name_plural': 'Обнаруженные объекты'},
        ),
    ]
